#!/usr/bin/python

import git_workflow_quality

import sys

graph = 'topo'
if len(sys.argv) > 1 and sys.argv[1] == 'date' :
    graph = 'date'

commits , order = git_workflow_quality.get_commits()

print
print "Number of commits: %s" % len(commits)
print "# initial commits: %s" % len([c for c in commits.values() if not c.parent ])
print "Number of merges:  %s" % len([c for c in commits.values() if c.parents])
print "Ammended commits:  %s" % len([c for c in commits.values() if c.author != c.committer and not c.parents])
print

