#!/usr/bin/python

import git_workflow_quality

import argparse
import sys

if __name__ == '__main__' :

    parser = argparse.ArgumentParser(description='Extract simple analytics from git repository')
    parser.add_argument('--detailed', action='store_true', help='Show per-branch statistics')
    parser.add_argument('--graph', choices=['topo', 'date'], help='Generate gitgraphjs file')
    args = parser.parse_args()

    repo = git_workflow_quality.repository()

    print repo.report(args.detailed)

    if args.graph :
        git_workflow_quality.gitgraphjs.graph( repo , args.graph )

