#!/usr/bin/python

import git_workflow_quality

import sys

repo = git_workflow_quality.repository()

print repo.report()

if len(sys.argv) > 1 :
    git_workflow_quality.gitgraphjs.graph( repo , sys.argv[1] )

